[phases.setup]
nixPkgs = ["php", "composer", "mysql", "nodejs"]

[phases.build]
cmds = [
  "composer install",
  "php artisan optimize:clear",
  "php artisan storage:link",
  "php artisan session:table",
  "php artisan migrate"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8000"
